version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"

  builder:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ../../:/app
    working_dir: /app

volumes:
  jenkins_home: